import hashlib
import io
import warnings
from itertools import islice

from PIL import Image, UnidentifiedImageError

from app.agent_models import Asset, uid


class AgentError(Exception):
    def __init__(self, code, message, status=409):
        self.code, self.message, self.status = code, message, status
        super().__init__(message)


class Storage:
    def __init__(self, settings):
        self.settings = settings
        self.root = settings.asset_root.resolve()
        self.hub = self.filesystem = None
        if settings.storage == "hf":
            from huggingface_hub import HfApi, HfFileSystem

            token = settings.hf_token.get_secret_value()
            self.hub = HfApi(token=token)
            self.filesystem = HfFileSystem(token=token, skip_instance_cache=True)

    def put(self, key, content, mime):
        if self.hub is not None:
            self.hub.batch_bucket_files(self.settings.hf_bucket, add=[(content, key)])
        else:
            path = self.root / key
            path.parent.mkdir(parents=True, exist_ok=True)
            temporary = path.with_suffix(".tmp")
            temporary.write_bytes(content)
            temporary.replace(path)

    def get(self, asset):
        if self.filesystem is not None:
            # Keys are generated by save(); never allow a database value to select
            # another bucket or escape the configured namespace.
            self._validate_key(asset.object_key)
            path = f"hf://buckets/{self.settings.hf_bucket}/{asset.object_key}"
            with self.filesystem.open(path, "rb", block_size=0) as body:
                return body.read(self.settings.max_image_bytes + 1)
        path = (self.root / asset.object_key).resolve()
        if not path.is_relative_to(self.root):
            raise AgentError("invalid_asset", "Invalid asset location")
        return path.read_bytes()

    @staticmethod
    def _validate_key(key):
        import re

        if not re.fullmatch(r"[0-9a-f]{24}/[0-9a-f]{32}", key):
            raise AgentError("invalid_asset", "Invalid asset location")

    def save(self, data, workspace, kind, source=None):
        if not data or len(data) > self.settings.max_image_bytes:
            raise AgentError("image_too_large", "Images must be at most 10 MB.", 413)
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("error", Image.DecompressionBombWarning)
                with Image.open(io.BytesIO(data)) as image:
                    if (
                        image.format not in {"PNG", "JPEG", "WEBP"}
                        or getattr(image, "n_frames", 1) != 1
                    ):
                        raise AgentError(
                            "unsupported_image",
                            "Use a still PNG, JPEG, or WebP image.",
                            415,
                        )
                    width, height = image.size
                    if width * height > self.settings.max_image_pixels:
                        raise AgentError(
                            "image_too_large", "Image exceeds the pixel limit.", 413
                        )
                    mime = Image.MIME[image.format]
                    image.verify()
        except (
            UnidentifiedImageError,
            OSError,
            ValueError,
            Image.DecompressionBombWarning,
            Image.DecompressionBombError,
        ):
            raise AgentError(
                "invalid_image", "The image could not be decoded.", 422
            ) from None
        asset_id = uid()
        # Workspace IDs never become filesystem paths.
        prefix = hashlib.sha256(workspace.encode()).hexdigest()[:24]
        key = f"{prefix}/{asset_id}"
        self.put(key, data, mime)
        return Asset(
            id=asset_id,
            workspace=workspace,
            kind=kind,
            object_key=key,
            checksum=hashlib.sha256(data).hexdigest(),
            mime=mime,
            width=width,
            height=height,
            source=source or {"type": "user_upload"},
        )

    def prune_orphans(self, workspace, known_keys, older_than):
        """Remove only stale, unreferenced objects in this workspace's generated namespace."""
        import re

        prefix = hashlib.sha256(workspace.encode()).hexdigest()[:24] + "/"
        pattern = re.compile(r"^[0-9a-f]{24}/[0-9a-f]{32}(?:\.tmp)?$")
        removed = 0
        if self.hub is not None:
            entries = self.hub.list_bucket_tree(
                self.settings.hf_bucket, prefix=prefix, recursive=False
            )
            for item in islice(entries, 1000):
                key = item.path
                # uploaded_at is server metadata; a caller-supplied mtime must
                # never make a recent upload eligible for deletion.
                if (
                    item.type == "file"
                    and key.startswith(prefix)
                    and pattern.fullmatch(key)
                    and key not in known_keys
                    and item.uploaded_at is not None
                    and item.uploaded_at.timestamp() < older_than
                ):
                    self.hub.batch_bucket_files(self.settings.hf_bucket, delete=[key])
                    removed += 1
        else:
            directory = self.root / prefix
            if directory.is_dir():
                for path in directory.iterdir():
                    key = prefix + path.name
                    if (
                        path.is_file()
                        and not path.is_symlink()
                        and pattern.fullmatch(key)
                        and key not in known_keys
                        and path.stat().st_mtime < older_than
                    ):
                        path.unlink()
                        removed += 1
        return removed
