import { expect, test } from "@playwright/test"
import { mockChat } from "./chat-fixture"

test("signs in, sends a durable turn, restores history, and edits the returned image", async ({ page }) => {
  const mock = await mockChat(page, { authenticated: false })
  await page.goto("/")
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await page.getByLabel("Workspace access key").fill("test-workspace-key")
  await page.getByRole("button", { name: "Sign in", exact: true }).click()
  await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("brand-1")
  await page.getByLabel("Message the collection companion").fill("Use image ID selected-image in my brand style, but use blue.")
  await page.getByRole("button", { name: "Send message" }).click()
  await expect(page.getByRole("log")).toContainText("Here is your brand image.")
  await expect(page.getByRole("img", { name: "Chat result" })).toBeVisible()
  expect(mock.sent[0].content).toContain("use blue")
  await page.reload()
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await page.getByLabel("Conversation", { exact: true }).selectOption("chat-1")
  await expect(page.getByRole("log")).toContainText("Here is your brand image.")
  await page.getByRole("button", { name: "Edit this image", exact: true }).click()
  await page.getByLabel("Message the collection companion").fill("Use a warmer background")
  await page.getByRole("button", { name: "Send message" }).click()
  await expect.poll(() => mock.sent.length).toBe(2)
  expect(mock.sent[1].subject_asset_id).toBe("generated-1")
})

test("retries a lost submission with the original key and cancels the pending task", async ({ page }) => {
  const mock = await mockChat(page, { loseResponse: true, pending: true })
  await page.goto("/")
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("brand-1")
  await page.getByLabel("Message the collection companion").fill("Create my brand image")
  await page.getByRole("button", { name: "Send message" }).click()
  await expect(page.getByRole("alert")).toBeVisible()
  await page.getByRole("button", { name: "Try again", exact: true }).click()
  await expect.poll(() => mock.submissions.length).toBe(2)
  expect(mock.submissions[0]).toBe(mock.submissions[1])
  expect(mock.sent.length).toBe(1)
  await page.getByRole("button", { name: "Cancel task" }).click()
  await expect(page.getByRole("log")).toContainText("Task cancelled")
  await expect(page.getByRole("button", { name: "New chat" })).toBeEnabled()
})

test("shows failed execution and allows a new turn", async ({ page }) => {
  const mock = await mockChat(page, { pending: true })
  await page.goto("/")
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("brand-1")
  await page.getByLabel("Message the collection companion").fill("Use missing image")
  await page.getByRole("button", { name: "Send message" }).click()
  mock.fail()
  await expect(page.getByRole("log")).toContainText("source_unavailable")
  await page.getByLabel("Message the collection companion").fill("Let me choose another")
  await expect(page.getByRole("button", { name: "Send message" })).toBeEnabled()
})

test("disabled agent leaves a search-only interface", async ({ page }) => {
  await mockChat(page, { disabled: true, authenticated: false })
  await page.goto("/")
  await expect(page.getByRole("heading", { name: "Science Museum Group datasets." })).toBeVisible()
  await expect(page.getByRole("button", { name: "Open collection chat" })).toHaveCount(0)
  await expect(page.getByRole("link", { name: "Image Studio" })).toHaveCount(0)
  await expect(page.getByRole("button", { name: /Use .* in chat/ })).toHaveCount(0)
})


test("retains generated images when evaluation fails", async ({ page }) => {
  await mockChat(page, { evaluationFailed: true })
  await page.goto("/")
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("brand-1")
  await page.getByLabel("Message the collection companion").fill("Create a brand image")
  await page.getByRole("button", { name: "Send message" }).click()
  await expect(page.getByText("Needs review · Not approved")).toBeVisible()
  await expect(page.getByRole("img", { name: "Chat result" })).toBeVisible()
  await expect(page.getByRole("link", { name: "Download image" })).toBeVisible()
  await expect(page.getByRole("log")).toContainText("You do not need to generate them again")
  await page.screenshot({ path: "/tmp/chat-evaluation-failure.png", fullPage: true })
})

test("shows review warnings for completed images after reloading history", async ({ page }) => {
  await mockChat(page, { needsReview: true })
  await page.goto("/")
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("brand-1")
  await page.getByLabel("Message the collection companion").fill("Create a brand image")
  await page.getByRole("button", { name: "Send message" }).click()
  await expect(page.getByText("Needs review · Not approved")).toBeVisible()
  await expect(page.getByRole("log")).not.toContainText("Task failed")
  await page.reload()
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await page.getByLabel("Conversation", { exact: true }).selectOption("chat-1")
  await expect(page.getByText("Needs review · Not approved")).toBeVisible()
  await expect(page.getByRole("link", { name: "Download image" })).toBeVisible()
  await expect(page.getByRole("button", { name: "Edit this image", exact: true })).toBeEnabled()
  await page.screenshot({ path: "/tmp/chat-quality-review.png", fullPage: true })
})

for (const [status, code] of [[429, "queue_full"], [503, "not_configured"]] as const) {
  test(`unlocks chat after a confirmed ${code} rejection`, async ({ page }) => {
    const mock = await mockChat(page)
    const keys: string[] = []
    await page.route("**/api/v1/agent/conversations/*/messages", async route => {
      keys.push(route.request().headers()["idempotency-key"])
      if (keys.length === 1) return route.fulfill({ status, json: { code, message: "Submission rejected." } })
      return route.fallback()
    })
    await page.goto("/")
    await page.getByRole("button", { name: "Open collection chat" }).click()
    await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("brand-1")
    const composer = page.getByLabel("Message the collection companion")
    await composer.fill("Create my brand image")
    await page.getByRole("button", { name: "Send message" }).click()
    await expect(page.getByRole("alert").filter({ hasText: "Submission rejected." })).toBeVisible()
    expect(mock.sent).toHaveLength(0)
    await expect(composer).toBeEnabled()
    await expect(composer).toHaveValue("Create my brand image")
    await expect(page.getByLabel("Conversation", { exact: true })).toBeEnabled()
    await expect(page.getByRole("button", { name: "New chat" })).toBeEnabled()
    await composer.fill("Create a different image")
    await page.getByRole("button", { name: "Send message" }).click()
    await expect(page.getByRole("log")).toContainText("Here is your brand image.")
    expect(mock.sent).toHaveLength(1)
    expect(mock.sent[0].content).toBe("Create a different image")
    expect(keys[1]).not.toBe(keys[0])
  })
}

test("keeps the original submission key after an uncertain server failure", async ({ page }) => {
  const mock = await mockChat(page)
  const keys: string[] = []
  await page.route("**/api/v1/agent/conversations/*/messages", async route => {
    keys.push(route.request().headers()["idempotency-key"])
    if (keys.length === 1) return route.fulfill({ status: 503, json: { message: "Response unavailable." } })
    return route.fallback()
  })
  await page.goto("/")
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("brand-1")
  const composer = page.getByLabel("Message the collection companion")
  await composer.fill("Create a brand image")
  await page.getByRole("button", { name: "Send message" }).click()
  const error = page.getByRole("alert").filter({ hasText: "Response unavailable." })
  await expect(error).toBeVisible()
  await expect(composer).toBeDisabled()
  await error.getByRole("button", { name: "Try again" }).click()
  await expect(page.getByRole("log")).toContainText("Here is your brand image.")
  expect(keys[1]).toBe(keys[0])
  expect(mock.sent).toHaveLength(1)
})
