import { expect, test } from "@playwright/test"
import { mockChat } from "./chat-fixture"

test("signs in, sends a durable turn, restores history, and edits the returned image", async ({ page }) => {
  const mock = await mockChat(page, { authenticated: false })
  await page.goto("/")
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await page.getByLabel("Workspace access key").fill("test-workspace-key")
  await page.getByRole("button", { name: "Sign in", exact: true }).click()
  await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("brand-1")
  await page.getByLabel("Message the collection companion").fill("Use image ID selected-image in my brand style, but use blue.")
  await page.getByRole("button", { name: "Send message" }).click()
  await expect(page.getByRole("log")).toContainText("Here is your brand image.")
  await expect(page.getByRole("img", { name: "Chat result" })).toBeVisible()
  expect(mock.sent[0].content).toContain("use blue")
  await page.reload()
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await page.getByLabel("Conversation", { exact: true }).selectOption("chat-1")
  await expect(page.getByRole("log")).toContainText("Here is your brand image.")
  await page.getByRole("button", { name: "Edit this image", exact: true }).click()
  await page.getByLabel("Message the collection companion").fill("Use a warmer background")
  await page.getByRole("button", { name: "Send message" }).click()
  await expect.poll(() => mock.sent.length).toBe(2)
  expect(mock.sent[1].subject_asset_id).toBe("generated-1")
})

test("retries a lost submission with the original key and cancels the pending task", async ({ page }) => {
  const mock = await mockChat(page, { loseResponse: true, pending: true })
  await page.goto("/")
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("brand-1")
  await page.getByLabel("Message the collection companion").fill("Create my brand image")
  await page.getByRole("button", { name: "Send message" }).click()
  await expect(page.getByRole("alert")).toBeVisible()
  await page.getByRole("button", { name: "Try again", exact: true }).click()
  await expect.poll(() => mock.submissions.length).toBe(2)
  expect(mock.submissions[0]).toBe(mock.submissions[1])
  expect(mock.sent.length).toBe(1)
  await page.getByRole("button", { name: "Cancel task" }).click()
  await expect(page.getByRole("log")).toContainText("Task cancelled")
  await expect(page.getByRole("button", { name: "New chat" })).toBeEnabled()
})

test("shows failed execution and allows a new turn", async ({ page }) => {
  const mock = await mockChat(page, { pending: true })
  await page.goto("/")
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("brand-1")
  await page.getByLabel("Message the collection companion").fill("Use missing image")
  await page.getByRole("button", { name: "Send message" }).click()
  mock.fail()
  await expect(page.getByRole("log")).toContainText("source_unavailable")
  await page.getByLabel("Message the collection companion").fill("Let me choose another")
  await expect(page.getByRole("button", { name: "Send message" })).toBeEnabled()
})

test("disabled agent never fabricates a reply", async ({ page }) => {
  await mockChat(page, { disabled: true, authenticated: false })
  await page.goto("/")
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await expect(page.getByText("Image creation is not configured yet.")).toBeVisible()
  await page.getByLabel("Message the collection companion").fill("Hello")
  await expect(page.getByRole("button", { name: "Send message" })).toBeDisabled()
  await expect(page.getByRole("log")).toBeEmpty()
})


test("retains generated images when evaluation fails", async ({ page }) => {
  await mockChat(page, { evaluationFailed: true })
  await page.goto("/")
  await page.getByRole("button", { name: "Open collection chat" }).click()
  await expect(page.getByLabel("Brand", { exact: true })).toHaveValue("brand-1")
  await page.getByLabel("Message the collection companion").fill("Create a brand image")
  await page.getByRole("button", { name: "Send message" }).click()
  await expect(page.getByText("Needs review · Not approved")).toBeVisible()
  await expect(page.getByRole("img", { name: "Chat result" })).toBeVisible()
  await expect(page.getByRole("link", { name: "Download image" })).toBeVisible()
  await expect(page.getByRole("log")).toContainText("You do not need to generate them again")
  await page.screenshot({ path: "/tmp/chat-evaluation-failure.png", fullPage: true })
})
